package de.thb.mps.language.Junit.sandbox;

/*Generated by MPS */

import org.junit.Before;

public class RechnerTest {

  private Rechner2 underTest;


  @Before
  public void setUp() throws Exception {
    underTest = new Rechner2();
  }


    public Integer RechnerTest(int a, int b) {
    return ;
  }
int test() {
  }


}
