package de.thb.mps.language.Junit.sandbox;

/*Generated by MPS */

import org.junit.Before;
import org.junit.Test;

public class RechnerTest {

  private RechnerTest underTest;

  @Before
  public void setUp() throws Exception {
    underTest = new RechnerTest();
  }

  @Test
  public void Rechner() {
  }
}
