package de.thb.mps.language.Junit.sandbox;

/*Generated by MPS */

import org.junit.Before;
import org.junit.Test;
import org.junit.Assert;

/**
 * 
 */
public class RechnerTest {

  private Rechner2 underTest;


  @Before
  public void setUp() throws Exception {
    underTest = new Rechner2();
  }





  @Test
  public void () {
    int result = underTest.???();
    // 
    Assert.assertEquals(, result);

  }


}
