package de.thb.mps.language.Junit.sandbox;

/*Generated by MPS */

import org.junit.Before;

public class Test {

  private Test underTest;

  @Before
  public void setUp() throws Exception {
    underTest = new Test();
  }


  @org.junit.Test
  public void () {
  }
}
